name: synergy_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  synergy_client_dart: ^0.0.5
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
